name: Deploy to Netlify

on:
  push:
    branches:
      - main  # branch que você quer usar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Pegar o código
      - uses: actions/checkout@v3

      # Deploy no Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./          # raiz do repositório
          production-branch: main
          deploy-message: "Deploy via GitHub Actions"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
